### ISSUE TITLE
Docs typo - carefull, change to careful

### ISSUE THREAD

**Issue by platipusica** [jam-py/jam-py#292]
Hi,
carefull is used through a few files.

Also, pararameters.

For example, I used this:
https://stackoverflow.com/questions/61807943/spell-check-a-directory-containing-many-files
and found for example in intro/tutorial01:
sh ~/spell_check.sh 
customizing_forms.txt
      1 firstname
      6 png
filters.txt
      1 dlg
      4 png
index.txt
      1 CRM
      2 lookup
      1 maxdepth
      1 toctree
indexes.txt
      2 dlg
      2 png
lookup_fields.txt
      1 **contacs**
      1 CRM
      1 **cutomer**
      1 **Cutomer**
      2 **cutomers**
.
.

Thanks

**Comment by platipusica** [comment]
The biggest one:
refs/client $ sh ~/spell_check.sh 
abstractitem_api.txt
      2 abstr
      3 AbstractItem
      **1 Attrubutes**
      1 javascript
      1 js
      2 maxdepth
      **1 Mehods**
      2 toctree

**Comment by platipusica** [comment]
Ok, 
looks like I checked the old git clone, made a new one, this is still there:

refs/client/item/at_table_options.txt:                    corresponding row of the table. Please be **carefull** - the 
admin/saving_history.txt:The following **mesage** will appear when the item will be created: 
admin/code_editor.txt:`**Hear** are keyboard shortcuts for the ace editor`_.
admin/code_editor.txt:.. **_Hear** are Keyboard Shortcuts for the ace editor: https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts
faq/faq_using_other_libraries.txt:For **exapmple** the mail item server module import smtplib library to send emails:
how_to/how_to_migrate_to_another_database.txt:You can **mirgate** your data to another database.

**programming/interface/form_exapmles.txt  --------->  programming/interface/index.txt has form_examples and not loaded into the Docs!!!!!**



refs/server/filter_api.txt:Attrubutes and properties
refs/server/field_api.txt:Attrubutes and properties
refs/server/detail_api.txt:Attrubutes
refs/server/abstractitem_api.txt:Attrubutes
refs/server/report_api.txt:Attrubutes
refs/server/item_api.txt:Attrubutes and properties
refs/server/task_api.txt:Attrubutes
refs/client/field_api.txt:Attrubutes and properties
refs/client/detail_api.txt:Attrubutes
refs/client/abstractitem_api.txt:Attrubutes
refs/client/report_api.txt:Attrubutes
refs/client/item_api.txt:Attrubutes and properties
refs/client/task_api.txt:Attrubutes

refs/server/abstractitem_api.txt:Mehods 
refs/server/report_api.txt:Mehods 
refs/server/item_api.txt:Mehods 
refs/server/task_api.txt:Mehods 
refs/client/field_api.txt:Mehods 
refs/client/abstractitem_api.txt:Mehods 
refs/client/report_api.txt:Mehods 
refs/client/item_api.txt:Mehods 
refs/client/task_api.txt:Mehods

**Comment by platipusica** [comment]
https://jam-py.readthedocs.io/_/downloads/en/latest/pdf/ 
is not building any more, since missing:
.readthedocs.yaml

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
formats: all

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: requirements.txt
```
I'm using requirements.txt, might not be needed for Jam docs.
